services:
    boundary-visualiser:
        image: boundary-visualiser:latest
        ports:
            - 8000:8000
        command:
            [
                "uv",
                "run",
                "fastapi",
                "run",
                "server.py",
                "--host",
                "0.0.0.0",
                "--port",
                "8000",
            ]
