[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "geopandas>=1.1.1",
    "shapely>=2.1.1",
    "typing>=3.10.0.0",
    "uvicorn[standard]>=0.35.0",
]
